# Use OAuth authentication for the storage account
fs.azure.account.auth.type.${AZURE_STORAGE_ACCOUNT}.dfs.core.windows.net OAuth

# Specify the token provider
fs.azure.account.oauth.provider.type.${AZURE_STORAGE_ACCOUNT}.dfs.core.windows.net org.apache.hadoop.fs.azurebfs.oauth2.ClientCredsTokenProvider

# Add the service principal details
fs.azure.account.oauth2.client.id.${AZURE_STORAGE_ACCOUNT}.dfs.core.windows.net ${ADLS_CLIENT_ID}
fs.azure.account.oauth2.client.secret.${AZURE_STORAGE_ACCOUNT}.dfs.core.windows.net ${ADLS_CLIENT_SECRET}
fs.azure.account.oauth2.client.endpoint.${AZURE_STORAGE_ACCOUNT}.dfs.core.windows.net https://login.microsoftonline.com/${ADLS_TENANT_ID}/oauth2/token
